# Generated by Django 3.2 on 2024-09-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        ('reservas', '0003_reserva_tren'),
        ('asientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['numero_asiento'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AddField(
            model_name='asiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asiento',
            name='numero_asiento',
            field=models.CharField(default='null', max_length=20, verbose_name='Numero Asiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asiento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
        migrations.AlterModelTable(
            name='asiento',
            table='asiento',
        ),
    ]
