# Generated by Django 5.1.2 on 2024-10-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='ruta',
        ),
    ]
