# Generated by Django 5.1.2 on 2024-10-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0002_remove_asiento_ruta'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='reservas.reserva'),
        ),
    ]
