# Generated by Django 5.1.2 on 2024-10-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0003_alter_asiento_reserva'),
        ('reservas', '0003_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva'),
        ),
    ]
