# Generated by Django 5.1.2 on 2024-10-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0004_alter_asiento_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
