# Generated by Django 5.1.2 on 2024-10-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0006_remove_asiento_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='estado',
        ),
    ]
