# Generated by Django 3.2 on 2024-08-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50, verbose_name='Estacion de origen')),
                ('destino', models.CharField(max_length=50, verbose_name='Estacion de destino')),
                ('duracion', models.SmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trenes.tren')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'ruta',
            },
        ),
    ]
