# Generated by Django 3.2 on 2024-09-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('estacion1', 'Estación 1'), ('estacion2', 'Estación 2')], max_length=50, verbose_name='Estación de origen')),
                ('destino', models.CharField(choices=[('estacionA', 'Estación A'), ('estacionB', 'Estación B')], max_length=50, verbose_name='Estación de destino')),
                ('duracion', models.SmallIntegerField()),
                ('dia_salida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dia Salida')),
                ('horario_salida', models.TimeField(blank=True, null=True, verbose_name='Horario de Salida')),
                ('dia_retorno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dia Retorno')),
                ('horario_retorno', models.TimeField(blank=True, null=True, verbose_name='Horario de Salida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trenes.tren')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'ruta',
            },
        ),
    ]
