# Generated by Django 5.1.2 on 2024-10-25 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='dia_retorno',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='horario_retorno',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion',
            field=models.TimeField(),
        ),
    ]
