# Generated by Django 3.2 on 2024-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='dia_retorno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dia Retorno'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dia_salida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dia Salida'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dias_disponibles',
            field=models.CharField(max_length=50, null=True, verbose_name='Días Disponibles'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(choices=[('estacionA', 'Estación A'), ('estacionB', 'Estación B')], max_length=50, verbose_name='Estación de destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(choices=[('estacion1', 'Estación 1'), ('estacion2', 'Estación 2')], max_length=50, verbose_name='Estación de origen'),
        ),
    ]
