# Generated by Django 3.2 on 2024-09-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_auto_20240910_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='horario_retorno',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de Salida'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='horario_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de Salida'),
        ),
    ]
