# Generated by Django 5.1.2 on 2024-10-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_ruta_usuario'),
        ('trenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='tren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='trenes.tren'),
        ),
    ]
