# Generated by Django 5.1.2 on 2024-10-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_alter_ruta_tren'),
        ('trenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='tren',
        ),
        migrations.AddField(
            model_name='ruta',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trenes.tren'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=50, verbose_name='Estación de destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=50, verbose_name='Estación de origen'),
        ),
    ]
