# Generated by Django 5.1.2 on 2024-10-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_rename_reserva_ruta_tren'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='horario_salida',
            new_name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='dia_salida',
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Dia salida'),
        ),
    ]
