# Generated by Django 5.1.2 on 2024-10-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('rutas', '0004_alter_ruta_tren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tren',
        ),
        migrations.AddField(
            model_name='reserva',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='rutas.ruta'),
        ),
    ]
