# Generated by Django 3.2 on 2024-08-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trenes', '0001_initial'),
        ('reservas', '0002_auto_20240820_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trenes.tren'),
        ),
    ]
