# Generated by Django 5.1.2 on 2024-10-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0007_remove_asiento_estado'),
        ('reservas', '0004_reserva_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asiento',
        ),
        migrations.CreateModel(
            name='ReservaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del Asiento en la Reserva')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asientos', to='asientos.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asientos', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reserva Asiento',
                'verbose_name_plural': 'Reservas Asientos',
                'db_table': 'reserva_asiento',
                'unique_together': {('reserva', 'asiento')},
            },
        ),
    ]
