# Generated by Django 5.1.2 on 2024-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_reserva_asiento_reservaasiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default='Disponible', verbose_name='Estado del Asiento en la Reserva'),
        ),
    ]
