# Generated by Django 5.1.2 on 2024-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Disponible', max_length=20, verbose_name='Estado reserva'),
        ),
    ]
