# Generated by Django 3.2 on 2024-08-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_reserva', 'cliente'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
