# Generated by Django 3.2 on 2024-08-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido_materno')),
                ('correo', models.CharField(max_length=128, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['apellido_paterno', '-apellido_materno', 'nombres'],
            },
        ),
    ]
