# Generated by Django 3.2 on 2024-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default='defaultpassword', max_length=128, verbose_name='Contraseña'),
        ),
    ]
