# Generated by Django 3.2 on 2024-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('capacidad', models.SmallIntegerField(default=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tren',
                'verbose_name_plural': 'Trenes',
                'db_table': 'tren',
                'ordering': ['nombre'],
            },
        ),
    ]
