# Generated by Django 3.2 on 2024-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tren',
            name='capacidad',
            field=models.SmallIntegerField(default=20),
        ),
    ]
